name: buffaloes_farm_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+5

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  replay_bloc: ^0.2.4
  google_fonts: ^4.0.4
  flutter_secure_storage: ^8.0.0
  dio: ^5.2.1+1
  http: ^0.13.0
  intl: ^0.18.0
  flutter_displaymode: ^0.6.0
  dart_extensions_methods: ^2.0.0
  shared_preferences: ^2.1.2
  flutter_spinkit: ^5.2.0
  permission_handler: ^10.3.0
  image_picker: ^0.8.9
  bottom_bar_with_sheet: ^2.4.0
  salomon_bottom_bar: ^3.3.2
  flutter_multi_formatter: ^2.11.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  uuid: ^3.0.7
  pin_code_fields: ^7.4.0
  flutter_cupertino_date_picker_fork: ^1.0.7
  font_awesome_flutter: ^10.4.0
  age_calculator: ^1.0.0
  cached_network_image: ^3.2.3
  custom_sliding_segmented_control: ^1.7.4
  image_picker_for_web: ^2.2.0
  auto_size_text: ^3.0.0
  universal_html: ^2.2.3

  syncfusion_flutter_charts: ^21.2.10
  syncfusion_flutter_maps: ^21.2.10
  fl_chart: ^0.63.0

  modal_bottom_sheet: #^2.1.2
    git:
      url: https://github.com/duythien0912/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_white_96.png"

flutter:

  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.ttf
  assets:
    - assets/districts.json
    - assets/provinces.json
    - assets/subDistricts.json
    - assets/zipcodes.json
    - assets/logo.png
    - assets/image_icon/
    - assets/geojson/