name: buffaloes_farm_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  replay_bloc: ^0.2.2
  google_fonts: ^3.0.1
  flutter_secure_storage: ^6.0.0
  dio: ^4.0.6
  http: ^0.13.5
  intl: ^0.17.0
  flutter_displaymode: ^0.4.0
  dart_extensions_methods: ^2.0.0
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  permission_handler: ^10.1.0
  image_picker: ^0.8.6
  bottom_bar_with_sheet: ^2.4.0
  salomon_bottom_bar: ^3.3.1
  ionicons: ^0.2.1
  flutter_multi_formatter: ^2.8.0
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  firebase_storage: ^11.0.3
  uuid: 3.0.6
  pin_code_fields: ^7.4.0
  modal_bottom_sheet: ^2.1.2
  flutter_cupertino_date_picker_fork: ^1.0.7
  font_awesome_flutter: ^10.2.1
  age_calculator: ^1.0.0
  cached_network_image: ^3.2.2
  custom_sliding_segmented_control: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: fonts/Itim-Regular.ttf
  assets:
    - assets/districts.json
    - assets/provinces.json
    - assets/subDistricts.json
    - assets/zipcodes.json
    - assets/logo.png