name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - web
  pull_request:
    branches:
      - web

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter --version
      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: Enable flutter web
        run: flutter config --enable-web
      - name: 'Build Web App'
        run: flutter build web --release
      - name: 'Deploy to Firebase Hosting'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

